-- Vitrine — BigQuery table definitions
-- Project: vitrine-wamba-2026
-- Dataset: vitrine_dataset (EU region)
-- Run once to bootstrap the schema.

-- ──────────────────────────────────────────────────────────────────────
-- 1. products_raw  (staging copy from TheLook public dataset)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.products_raw` (
  product_id      INT64       NOT NULL,
  name            STRING      NOT NULL,
  brand           STRING,
  category        STRING      NOT NULL,
  department      STRING,
  retail_price    FLOAT64,
  cost            FLOAT64,
  created_at      TIMESTAMP,
  ingestion_date  DATE        NOT NULL
)
OPTIONS (
  description = "Raw product records copied verbatim from bigquery-public-data.thelook_ecommerce.products"
);

-- ──────────────────────────────────────────────────────────────────────
-- 2. products_clean  (deduplicated, normalised, validated)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.products_clean` (
  product_id         INT64       NOT NULL,
  name               STRING      NOT NULL,
  brand              STRING      NOT NULL,   -- "UNBRANDED" if originally NULL
  category           STRING      NOT NULL,
  department         STRING      NOT NULL,   -- "GENERAL" if originally NULL
  retail_price       FLOAT64     NOT NULL,
  cost               FLOAT64     NOT NULL,
  margin_pct         FLOAT64,                -- (retail_price - cost) / retail_price * 100
  is_valid           BOOL        NOT NULL,
  validation_errors  STRING,                 -- JSON array of error codes, NULL if clean
  cleaned_at         TIMESTAMP   NOT NULL,
  source_created_at  TIMESTAMP
)
OPTIONS (
  description = "Cleaned and validated product catalogue. Single source of truth for all downstream layers."
);

-- ──────────────────────────────────────────────────────────────────────
-- 3. products_embedded  (OpenAI text-embedding-3-small vectors)
--    NOTE: ARRAY<FLOAT64> is required for VECTOR_SEARCH.
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.products_embedded` (
  product_id            INT64           NOT NULL,
  embedding_text        STRING          NOT NULL,  -- concatenated input sent to OpenAI
  embedding             ARRAY<FLOAT64>,             -- 1536-dim vector (BigQuery: ARRAY cannot be NOT NULL)
  embedding_model       STRING          NOT NULL,  -- "text-embedding-3-small"
  embedding_tokens      INT64           NOT NULL,
  embedding_cost_usd    FLOAT64,
  embedding_created_at  TIMESTAMP       NOT NULL
)
OPTIONS (
  description = "Semantic embeddings (1536-dim) generated by OpenAI text-embedding-3-small for each product."
);

-- ──────────────────────────────────────────────────────────────────────
-- 4. products_clustered  (HDBSCAN cluster assignments)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.products_clustered` (
  product_id              INT64    NOT NULL,
  cluster_id              INT64    NOT NULL,   -- -1 for noise / unclustered
  cluster_label           STRING,              -- GPT-4o-mini label, NULL for noise
  cluster_probability     FLOAT64,             -- HDBSCAN confidence 0–1
  is_noise                BOOL     NOT NULL,
  clustering_algorithm    STRING   NOT NULL,   -- "HDBSCAN"
  min_cluster_size_param  INT64    NOT NULL,   -- 15
  clustering_created_at   TIMESTAMP NOT NULL
)
OPTIONS (
  description = "HDBSCAN cluster assignments. cluster_id=-1 means noise (outlier not in any cluster)."
);

-- ──────────────────────────────────────────────────────────────────────
-- 5. products_enriched  (GPT-4o-mini descriptions)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.products_enriched` (
  product_id                INT64    NOT NULL,
  cluster_id                INT64,             -- denormalised from products_clustered
  cluster_label             STRING,            -- denormalised
  description_enriched      STRING   NOT NULL,
  description_model         STRING   NOT NULL, -- "gpt-4o-mini"
  description_tone          STRING   NOT NULL, -- "luxury_retail"
  description_tokens_input  INT64,
  description_tokens_output INT64,
  description_cost_usd      FLOAT64,
  description_created_at    TIMESTAMP NOT NULL
)
OPTIONS (
  description = "AI-generated 50-word luxury retail descriptions, one per product."
);

-- ──────────────────────────────────────────────────────────────────────
-- 6. quality_report  (latest quality metrics snapshot)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.quality_report` (
  report_timestamp         TIMESTAMP NOT NULL,
  total_records            INT64     NOT NULL,
  valid_records            INT64     NOT NULL,
  completeness_pct         FLOAT64   NOT NULL,
  field_name_completeness  INT64,
  field_brand_completeness INT64,
  field_cat_completeness   INT64,
  field_price_completeness INT64,
  price_mean               FLOAT64,
  price_stddev             FLOAT64,
  price_min                FLOAT64,
  price_max                FLOAT64
)
OPTIONS (
  description = "Data quality metrics produced by 03_quality_checks.sql after each pipeline run."
);

-- ──────────────────────────────────────────────────────────────────────
-- 7. pipeline_runs  (idempotency + audit log)
-- ──────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `vitrine-wamba-2026.vitrine_dataset.pipeline_runs` (
  run_id             STRING    NOT NULL,
  started_at         TIMESTAMP NOT NULL,
  completed_at       TIMESTAMP,
  status             STRING    NOT NULL,  -- IN_PROGRESS | COMPLETE | FAILED
  products_processed INT64,
  clusters_created   INT64,
  error_message      STRING
)
OPTIONS (
  description = "Audit log for every pipeline execution. Used for idempotency checks."
);
